<div class="form-group">
    <?php 
    $this->element->name->setDecorators(
        array(
            'ViewHelper',
            'Description',
            //'Errors',
            array('HtmlTag', array(
                'tag' => 'div',
                'class' => 'col-sm-10'
            )),
            array('Label', array('class' => 'col-sm-2 control-label'))
        )
    );
    echo $this->element->name; 
    ?>
</div>
<div class="form-group">
    <div class="col-sm-10 col-sm-offset-2">
        <?php 
        $this->element->add->setDecorators(array('ViewHelper'));
        echo $this->element->add;
        ?>
    </div>
</div>
