<div class="page-header">
    <h1>Détails du film</h1>
</div>

<h2><?= $this->film->getTitle() ?></h2>
<p><?= $this->film->getDescription() ?></p>

<h3>Categories</h3>
<ul>
<?php $categories = $this->film->getCategories() ?>
<?php foreach ($categories as $category) : ?>
    <li><?= $category->getName() ?></li>
<?php endforeach; ?>
</ul>

<h3>Acteurs</h3>
<ul>
<?php $actors = $this->film->getActors() ?>
<?php foreach ($actors as $actor) : ?>
    <li><?= $actor->getFirstName() . ' ' . $actor->getLastName() ?></li>
<?php endforeach; ?>
</ul>

<p><a href="/">Retour à l'index</a>